-- CREATE TABLE IF NOT EXISTS pagamentos (
--     id           BIGINT       NOT NULL,
--     usuario_id   BIGINT       NOT NULL,
--     email        VARCHAR(255) NOT NULL,
--     nome_produto VARCHAR(255) NOT NULL,
--     tipo         VARCHAR(255) NOT NULL,
--     peso_kg      DOUBLE PRECISION,
--     valor        DOUBLE PRECISION,
--     cartao       VARCHAR(255) NOT NULL,
--     parcelas     BIGINT       NOT NULL,
--     horario      VARCHAR(255) NOT NULL,
--     status       VARCHAR(255) NOT NULL,
--     CONSTRAINT pk_pagamentos PRIMARY KEY (id),
--     CONSTRAINT fk_pagamentos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
-- );
--
-- ALTER TABLE pagamentos
--     ADD CONSTRAINT uc_pagamentos_usuario UNIQUE (usuario_id);
--
--
-- CREATE TABLE IF NOT EXISTS USUARIOS (
--     id              BIGINT       NOT NULL,
--     nome_completo   VARCHAR(255) NOT NULL,
--     email           VARCHAR(255) UNIQUE NOT NULL,
--     cpf             VARCHAR(255) UNIQUE NOT NULL,
--     data_nascimento VARCHAR(255) NOT NULL,
--     endereco_id     BIGINT       NOT NULL,
--     CONSTRAINT fk_usuarios_endereco FOREIGN KEY (endereco_id) REFERENCES enderecos(id)
-- );
--
-- CREATE TABLE IF NOT EXISTS ENDERECOS (
--     id              BIGINT       NOT NULL,
--     estado          VARCHAR(255) NOT NULL,
--     cidade          VARCHAR(255) NOT NULL,
--     logradouro      VARCHAR(255) UNIQUE ,
--     cep             VARCHAR(255) NOT NULL,
--     numero          VARCHAR(255) NOT NULL
-- );